### ISSUE TITLE
Error in label: label() got unexpected keyword argument 'single_file' with bazel 7.1.1

### ISSUE THREAD

**Issue by JordanPhilipSmith** [jmillikin/rules_m4#17]
I am using bazel 7.1.1.  I am trying to use an external repo for GMP (GNU multiprecision) with bazel.  I cloned this repo:

cd ~/dev
git clone https://github.com/robin-thomas/bazelify-gmp.git

When I try to compile it, I get an error with M4:

cd ~/dev/bazelify-gmp; bazel test //gmp_6_1_2/... --sandbox_debug --verbose_failures
Computing main repo mapping: 
ERROR: Traceback (most recent call last):
	File "/private/var/tmp/_bazel_jordansmith/dc88ff116f8da0e038742f8fca8fbbf9/external/io_bazel_rules_m4/m4.bzl", line 82, column 31, in <toplevel>
		"template": attr.label(
Error in label: label() got unexpected keyword argument 'single_file'
ERROR: Error computing the main repository mapping: initialization of module 'm4.bzl' failed

Thank you for your help,
Jordan

**Comment by jmillikin** [comment]
That repo is depending on an extremely old (and untagged) version of `rules_m4`. From https://github.com/robin-thomas/bazelify-gmp/blob/master/WORKSPACE:

```starlark
git_repository(
    name = "io_bazel_rules_m4",
    remote = "https://github.com/jmillikin/rules_m4",
    commit = "2bf69df77dfb6b3ba6b7fc95c304b0dc279375bc",
)
```

Please try updating the dependency to one of the released versions of `rules_m4`.
